print("to claculate average marks in 5 subjects")
a=input("Enter your marks in first subject = ")
a=int(a)
b=input("Enter your marks in second subject = ")
b=int(b)
c=input("Enter your marks in third subject = ")
c=int(c)
d=input("Enter your marks in fourth subject = ")
d=int(d)
e=input("Enter your marks in fifth subject = ")
e=int(e)
print("Your marks in first subject", a)
print("Your marks in second subject", b)
print( "Your marks in third subject", c)
print("Your marks in fourth subject", d)
print("Your marks in fifth subject", e)
f=(a+b+c+d+e)/5
f=float(f)
print("Your average marks are", f)
